Fecha: 29 de Mayo de 2026
Autor: Jose Valentin Contreras Gomez

In [5]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\val\anaconda\lib\site-packages (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\val\anaconda\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\val\anaconda\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import matplotlib.pyplot as plt

In [3]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\users\val\anaconda\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\val\anaconda\lib\site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in c:\users\val\anaconda\lib\site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\val\anaconda\lib\site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\val\anaconda\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\val\anaconda\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\val\anaconda\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\val\anaconda\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\val\anaconda\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\val\anaconda\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\val\anaconda\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\val\anaconda\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\val\anaconda\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\val\anaconda\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\val\anaconda\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
import seaborn as sns

In [7]:
dfCrudo = pd.read_csv("../Data/dataset_sucio_practica.csv")

In [5]:
dfCrudo

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
0,1,Julia Zhang,150.0,aortiz@perry.com,NaN,25000.0,2026-03-09,Sí
1,2,NaN,35.0,asimmons@garza.com,España,NaN,2026-05-04,No
2,3,George Burke,40.0,mcclainerin@gmail.com,Argentina,NaN,2026-01-27,NaN
3,4,Joyce Williams,30.0,correo_invalido,Argentina,25000.0,2025-02-23,No
4,5,Elaine Sanchez,-5.0,correo_invalido,México,25000.0,2025-03-28,Sí
...,...,...,...,...,...,...,...,...
120,1,Julia Zhang,150.0,aortiz@perry.com,NaN,25000.0,2026-03-09,Sí
121,2,NaN,35.0,asimmons@garza.com,España,NaN,2026-05-04,No
122,3,George Burke,40.0,mcclainerin@gmail.com,Argentina,NaN,2026-01-27,NaN
123,4,Joyce Williams,30.0,correo_invalido,Argentina,25000.0,2025-02-23,No
124,5,Elaine Sanchez,-5.0,correo_invalido,México,25000.0,2025-03-28,Sí

In [8]:
dfCrudoCopia = dfCrudo.copy()

In [9]:
dfCrudoCopia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              125 non-null    int64
 1   nombre          116 non-null    object
 2   edad            110 non-null    float64
 3   correo          125 non-null    object
 4   pais            82 non-null     object
 5   salario         107 non-null    float64
 6   fecha_registro  125 non-null    object
 7   activo          90 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 7.9+ KB

In [10]:
dfCrudoCopia.describe()

               id        edad       salario
count  125.000000  110.000000    107.000000
mean    58.200000   43.945455  14093.457944
std     35.906465   47.489803   8825.918852
min      1.000000   -5.000000  -1000.000000
25%     27.000000   22.750000  12000.000000
50%     58.000000   30.000000  15000.000000
75%     89.000000   40.000000  18000.000000
max    120.000000  150.000000  25000.000000

In [11]:
dfCrudoCopia.isnull().sum()

id                 0
nombre             9
edad              15
correo             0
pais              43
salario           18
fecha_registro     0
activo            35
dtype: int64

In [2]:
plt.figure(figsize=(12,6))
sns.heatmap(dfCrudoCopia.isnull(), cbar=False)
plt.title("mapa de calor de valores nulos")
plt.show()

NameError: name 'plt' is not defined

limpieza de datos 
1. eliminar valores duplicados
2. imputar valores nulos
3. corregir outlier (valores fuera de rango)

In [7]:
dfCrudoCopia.duplicated().sum()

np.int64(5)

In [24]:
dfCrudoCopia.drop_duplicates(inplace=True)

In [2]:
dfCrudoCopia

NameError: name 'dfCrudoCopia' is not defined

In [6]:
dfCrudoCopia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              125 non-null    int64
 1   nombre          116 non-null    object
 2   edad            110 non-null    float64
 3   correo          125 non-null    object
 4   pais            82 non-null     object
 5   salario         107 non-null    float64
 6   fecha_registro  125 non-null    object
 7   activo          90 non-null     object
dtypes: float64(2), int64(1), object(5)
memory usage: 7.9+ KB

In [2]:
pip install panda

Defaulting to user installation because normal site-packages is not writeable
Collecting panda
  Downloading panda-0.3.1.tar.gz (5.8 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: setuptools in c:\users\val\anaconda\lib\site-packages (from panda) (80.9.0)
Requirement already satisfied: requests in c:\users\val\anaconda\lib\site-packages (from panda) (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\val\anaconda\lib\site-packages (from requests->panda) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\val\anaconda\lib\site-packages (from requests->panda) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\val\anaconda\lib\site-packages (from requests->panda) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\val\anaconda\lib\site-packages (from requests->panda) (2026.5.20)
Building wheels for collected packages: panda
  Building wheel for panda (pyproject.toml): started
  Building wheel for panda (pyproject.toml): finished with status 'done'
  Created wheel for panda: filename=panda-0.3.1-py3-none-any.whl size=7295 sha256=effc4db68c959bd329a65f6c66d8d20c9e4e157b49b2785db128ce3dcc5da064
  Stored in directory: c:\users\lapone mx\appdata\local\pip\cache\wheels\53\7c\f7\d3267739bc9dfdfc43724391337c9955e7d5b5830888d735e3
Successfully built panda
Installing collected packages: panda
Successfully installed panda-0.3.1
Note: you may need to restart the kernel to use updated packages.

In [9]:
dfCrudoCopia.duplicated().sum()

np.int64(0)

In [10]:
dfCrudoCopia[
    (dfCrudoCopia["edad"]<0) | (dfCrudoCopia["edad"]>100)
    ]

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
0,1,Julia Zhang,150.0,aortiz@perry.com,NaN,25000.0,2026-03-09,Sí
4,5,Elaine Sanchez,-5.0,correo_invalido,México,25000.0,2025-03-28,Sí
6,7,Roberto Smith,-5.0,vegasara@yahoo.com,NaN,12000.0,2026-03-31,NaN
7,8,Nicholas Torres,-5.0,arnoldjoe@macias.biz,NaN,12000.0,2026-04-07,NaN
9,10,Angela Richards,-5.0,rubiogabrielle@yahoo.com,Argentina,-1000.0,2025-09-22,Sí
12,13,Paul Liu,150.0,ilong@gmail.com,España,NaN,2025-11-21,No
16,17,Christopher Klein,-5.0,ericarice@hotmail.com,España,18000.0,2024-09-22,Sí
22,23,Mrs. Diane Carter,150.0,schultzpatrick@mccoy.net,NaN,18000.0,2024-10-31,No
23,24,Vicki Love,-5.0,antonio14@johnson.net,Argentina,NaN,2026-01-24,No
24,25,Matthew Porter,-5.0,hansoncameron@yahoo.com,Argentina,12000.0,2025-11-17,No
38,39,Rose Williams,-5.0,jesus70@berger.org,España,12000.0,2025-01-09,No
39,40,Cynthia Cooke,-5.0,charlesthompson@ramirez.com,España,12000.0,2026-01-07,Sí
40,41,Cynthia Arnold,150.0,correo_invalido,NaN,25000.0,2024-11-03,No
41,42,Patricia Morrison,150.0,uweiss@yahoo.com,Argentina,-1000.0,2026-03-10,No
55,56,Kristen Kelly,-5.0,nvincent@gmail.com,NaN,25000.0,2026-05-02,Sí
59,60,Michael Dixon,-5.0,schneiderstephanie@coleman-snyder.biz,México,-1000.0,2026-05-02,Sí
61,62,John Anderson,150.0,mario37@hotmail.com,México,18000.0,2025-05-05,No
67,68,Timothy Li,150.0,molsen@gmail.com,México,12000.0,2024-10-26,NaN
73,74,NaN,-5.0,cookkevin@miller.com,México,25000.0,2026-01-21,Sí
74,75,Adrienne Clark,150.0,michaelwilkerson@martin.com,NaN,15000.0,2024-11-30,NaN
80,81,Mike Davis,-5.0,justinadams@cooper-scott.net,NaN,12000.0,2024-12-29,No
82,83,NaN,150.0,kristinajones@hotmail.com,México,15000.0,2024-09-01,Sí
83,84,Regina Cooper,-5.0,hsmith@hotmail.com,México,NaN,2024-08-04,Sí
84,85,Joel West,150.0,odonnellvicki@yahoo.com,NaN,-1000.0,2024-11-12,NaN
88,89,Erika Bernard,150.0,correo_invalido,Argentina,12000.0,2024-11-16,Sí
89,90,Michael Johnson,150.0,christinevelazquez@hotmail.com,NaN,NaN,2024-11-02,NaN
94,95,Daniel Wong,150.0,correo_invalido,España,NaN,2026-04-29,No
103,104,Jennifer Booth,150.0,udowns@cannon.com,México,-1000.0,2025-05-04,No
107,108,Taylor Collins,150.0,ngarza@hotmail.com,España,25000.0,2025-09-06,Sí
117,118,Michael Harper,-5.0,ndaniels@gmail.com,Argentina,12000.0,2026-04-29,No
118,119,Kristopher Hampton,150.0,josephwilliam@taylor-collins.com,NaN,-1000.0,2025-07-08,NaN

In [12]:
dfCrudoCopia.loc[
    (dfCrudoCopia["edad"]<0) | (dfCrudoCopia ["edad"]>100)
     ]

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
0,1,Julia Zhang,150.0,aortiz@perry.com,NaN,25000.0,2026-03-09,Sí
4,5,Elaine Sanchez,-5.0,correo_invalido,México,25000.0,2025-03-28,Sí
6,7,Roberto Smith,-5.0,vegasara@yahoo.com,NaN,12000.0,2026-03-31,NaN
7,8,Nicholas Torres,-5.0,arnoldjoe@macias.biz,NaN,12000.0,2026-04-07,NaN
9,10,Angela Richards,-5.0,rubiogabrielle@yahoo.com,Argentina,-1000.0,2025-09-22,Sí
12,13,Paul Liu,150.0,ilong@gmail.com,España,NaN,2025-11-21,No
16,17,Christopher Klein,-5.0,ericarice@hotmail.com,España,18000.0,2024-09-22,Sí
22,23,Mrs. Diane Carter,150.0,schultzpatrick@mccoy.net,NaN,18000.0,2024-10-31,No
23,24,Vicki Love,-5.0,antonio14@johnson.net,Argentina,NaN,2026-01-24,No
24,25,Matthew Porter,-5.0,hansoncameron@yahoo.com,Argentina,12000.0,2025-11-17,No
38,39,Rose Williams,-5.0,jesus70@berger.org,España,12000.0,2025-01-09,No
39,40,Cynthia Cooke,-5.0,charlesthompson@ramirez.com,España,12000.0,2026-01-07,Sí
40,41,Cynthia Arnold,150.0,correo_invalido,NaN,25000.0,2024-11-03,No
41,42,Patricia Morrison,150.0,uweiss@yahoo.com,Argentina,-1000.0,2026-03-10,No
55,56,Kristen Kelly,-5.0,nvincent@gmail.com,NaN,25000.0,2026-05-02,Sí
59,60,Michael Dixon,-5.0,schneiderstephanie@coleman-snyder.biz,México,-1000.0,2026-05-02,Sí
61,62,John Anderson,150.0,mario37@hotmail.com,México,18000.0,2025-05-05,No
67,68,Timothy Li,150.0,molsen@gmail.com,México,12000.0,2024-10-26,NaN
73,74,NaN,-5.0,cookkevin@miller.com,México,25000.0,2026-01-21,Sí
74,75,Adrienne Clark,150.0,michaelwilkerson@martin.com,NaN,15000.0,2024-11-30,NaN
80,81,Mike Davis,-5.0,justinadams@cooper-scott.net,NaN,12000.0,2024-12-29,No
82,83,NaN,150.0,kristinajones@hotmail.com,México,15000.0,2024-09-01,Sí
83,84,Regina Cooper,-5.0,hsmith@hotmail.com,México,NaN,2024-08-04,Sí
84,85,Joel West,150.0,odonnellvicki@yahoo.com,NaN,-1000.0,2024-11-12,NaN
88,89,Erika Bernard,150.0,correo_invalido,Argentina,12000.0,2024-11-16,Sí
89,90,Michael Johnson,150.0,christinevelazquez@hotmail.com,NaN,NaN,2024-11-02,NaN
94,95,Daniel Wong,150.0,correo_invalido,España,NaN,2026-04-29,No
103,104,Jennifer Booth,150.0,udowns@cannon.com,México,-1000.0,2025-05-04,No
107,108,Taylor Collins,150.0,ngarza@hotmail.com,España,25000.0,2025-09-06,Sí
117,118,Michael Harper,-5.0,ndaniels@gmail.com,Argentina,12000.0,2026-04-29,No
118,119,Kristopher Hampton,150.0,josephwilliam@taylor-collins.com,NaN,-1000.0,2025-07-08,NaN

In [13]:
dfCrudoCopia[
    (dfCrudoCopia["edad"]<0) | (dfCrudoCopia["edad"]>100)
    ]

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
0,1,Julia Zhang,150.0,aortiz@perry.com,NaN,25000.0,2026-03-09,Sí
4,5,Elaine Sanchez,-5.0,correo_invalido,México,25000.0,2025-03-28,Sí
6,7,Roberto Smith,-5.0,vegasara@yahoo.com,NaN,12000.0,2026-03-31,NaN
7,8,Nicholas Torres,-5.0,arnoldjoe@macias.biz,NaN,12000.0,2026-04-07,NaN
9,10,Angela Richards,-5.0,rubiogabrielle@yahoo.com,Argentina,-1000.0,2025-09-22,Sí
12,13,Paul Liu,150.0,ilong@gmail.com,España,NaN,2025-11-21,No
16,17,Christopher Klein,-5.0,ericarice@hotmail.com,España,18000.0,2024-09-22,Sí
22,23,Mrs. Diane Carter,150.0,schultzpatrick@mccoy.net,NaN,18000.0,2024-10-31,No
23,24,Vicki Love,-5.0,antonio14@johnson.net,Argentina,NaN,2026-01-24,No
24,25,Matthew Porter,-5.0,hansoncameron@yahoo.com,Argentina,12000.0,2025-11-17,No
38,39,Rose Williams,-5.0,jesus70@berger.org,España,12000.0,2025-01-09,No
39,40,Cynthia Cooke,-5.0,charlesthompson@ramirez.com,España,12000.0,2026-01-07,Sí
40,41,Cynthia Arnold,150.0,correo_invalido,NaN,25000.0,2024-11-03,No
41,42,Patricia Morrison,150.0,uweiss@yahoo.com,Argentina,-1000.0,2026-03-10,No
55,56,Kristen Kelly,-5.0,nvincent@gmail.com,NaN,25000.0,2026-05-02,Sí
59,60,Michael Dixon,-5.0,schneiderstephanie@coleman-snyder.biz,México,-1000.0,2026-05-02,Sí
61,62,John Anderson,150.0,mario37@hotmail.com,México,18000.0,2025-05-05,No
67,68,Timothy Li,150.0,molsen@gmail.com,México,12000.0,2024-10-26,NaN
73,74,NaN,-5.0,cookkevin@miller.com,México,25000.0,2026-01-21,Sí
74,75,Adrienne Clark,150.0,michaelwilkerson@martin.com,NaN,15000.0,2024-11-30,NaN
80,81,Mike Davis,-5.0,justinadams@cooper-scott.net,NaN,12000.0,2024-12-29,No
82,83,NaN,150.0,kristinajones@hotmail.com,México,15000.0,2024-09-01,Sí
83,84,Regina Cooper,-5.0,hsmith@hotmail.com,México,NaN,2024-08-04,Sí
84,85,Joel West,150.0,odonnellvicki@yahoo.com,NaN,-1000.0,2024-11-12,NaN
88,89,Erika Bernard,150.0,correo_invalido,Argentina,12000.0,2024-11-16,Sí
89,90,Michael Johnson,150.0,christinevelazquez@hotmail.com,NaN,NaN,2024-11-02,NaN
94,95,Daniel Wong,150.0,correo_invalido,España,NaN,2026-04-29,No
103,104,Jennifer Booth,150.0,udowns@cannon.com,México,-1000.0,2025-05-04,No
107,108,Taylor Collins,150.0,ngarza@hotmail.com,España,25000.0,2025-09-06,Sí
117,118,Michael Harper,-5.0,ndaniels@gmail.com,Argentina,12000.0,2026-04-29,No
118,119,Kristopher Hampton,150.0,josephwilliam@taylor-collins.com,NaN,-1000.0,2025-07-08,NaN

In [10]:
dfCrudoCopia.loc[
    (dfCrudoCopia["edad"]<0) | (dfCrudoCopia ["edad"]>100)
     ] = np.nan

In [11]:
dfCrudoCopia[
    (dfCrudoCopia["edad"]<0) | (dfCrudoCopia["edad"]>100)
    ]

Empty DataFrame
Columns: [id, nombre, edad, correo, pais, salario, fecha_registro, activo]
Index: []

In [12]:
mediana_edad = dfCrudoCopia["edad"].median()
mediana_edad

30.0

In [13]:
dfCrudoCopia["edad"] = dfCrudoCopia["edad"].fillna(mediana_edad)

In [14]:
dfCrudoCopia["edad"].describe()

count    125.000000
mean      30.432000
std        4.747386
min       22.000000
25%       30.000000
50%       30.000000
75%       35.000000
max       40.000000
Name: edad, dtype: float64

In [18]:
dfCrudoCopia[
    (dfCrudoCopia["salario"]<0)
    ]

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
11,12.0,Daniel Wright,25.0,melissamaxwell@gmail.com,NaN,-1000.0,2024-12-20,Sí
20,21.0,Marc Miller DDS,30.0,ccalderon@campbell-carter.com,NaN,-1000.0,2024-06-25,Sí
21,22.0,Carrie Griffith,30.0,correo_invalido,NaN,-1000.0,2025-05-05,NaN
26,27.0,Mary Miranda,40.0,brendaglenn@gmail.com,Argentina,-1000.0,2025-06-01,NaN
27,28.0,John Taylor,30.0,jonesashley@hotmail.com,NaN,-1000.0,2025-08-02,No
28,29.0,Teresa Ramos,22.0,rileyraymond@hotmail.com,México,-1000.0,2025-08-29,NaN
37,38.0,Brian Sherman,30.0,brianna61@yahoo.com,Argentina,-1000.0,2024-09-17,Sí
44,45.0,John Estrada,35.0,nichole26@hotmail.com,Argentina,-1000.0,2025-12-12,Sí
45,46.0,Jeremy Cooper,35.0,vfrederick@hotmail.com,NaN,-1000.0,2025-02-03,No
48,49.0,Willie Marks,30.0,joshua86@farrell.com,NaN,-1000.0,2024-08-05,Sí
54,55.0,John Lewis,30.0,rodriguezbrett@yahoo.com,México,-1000.0,2024-07-03,NaN
60,61.0,Thomas Perkins,35.0,lyoung@moore.com,España,-1000.0,2025-06-06,No
65,66.0,Michael Lopez,40.0,correo_invalido,España,-1000.0,2025-12-01,No
78,79.0,Charles Page,25.0,correo_invalido,NaN,-1000.0,2025-09-01,No
111,112.0,Shawn Diaz,40.0,rpatterson@cabrera.net,España,-1000.0,2024-07-15,No

In [20]:
dfCrudoCopia.loc[
    (dfCrudoCopia["salario"]<0), "salario"
     ] = np.nan

In [21]:
mediana_salario = dfCrudoCopia["salario"].median()
mediana_salario

16500.0

In [22]:
dfCrudoCopia["salario"] = dfCrudoCopia["salario"].fillna(mediana_salario)

In [25]:
dfCrudoCopia["salario"].describe()

count       90.000000
mean     17305.555556
std       4164.250236
min      12000.000000
25%      15000.000000
50%      16500.000000
75%      18000.000000
max      25000.000000
Name: salario, dtype: float64

In [27]:
dfCrudoCopia[
    ~dfCrudoCopia["correo"].str.contains("@", na= False)
    ]

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
0,NaN,NaN,30.0,NaN,NaN,16500.0,NaN,NaN
3,4.0,Joyce Williams,30.0,correo_invalido,Argentina,25000.0,2025-02-23,No
18,19.0,Nicholas Curry,35.0,correo_invalido,México,12000.0,2025-11-22,Sí
21,22.0,Carrie Griffith,30.0,correo_invalido,NaN,16500.0,2025-05-05,NaN
30,31.0,Mrs. Sara Johnson,35.0,correo_invalido,Argentina,16500.0,2026-03-07,NaN
65,66.0,Michael Lopez,40.0,correo_invalido,España,16500.0,2025-12-01,No
78,79.0,Charles Page,25.0,correo_invalido,NaN,16500.0,2025-09-01,No
87,88.0,NaN,22.0,correo_invalido,NaN,12000.0,2025-03-07,NaN
95,96.0,Luis Drake,25.0,correo_invalido,NaN,25000.0,2025-01-22,Sí

In [29]:
correos_invalidos = ~dfCrudoCopia["correo"].str.contains("@", na= False)
correos_invalidos

0       True
1      False
2      False
3       True
5      False
       ...
113    False
114    False
115    False
116    False
119    False
Name: correo, Length: 90, dtype: bool

In [30]:
dfCrudoCopia.loc[correos_invalidos, "correo"] = pd.NA

In [31]:
dfCrudoCopia

,id,nombre,edad,correo,pais,salario,fecha_registro,activo
0,NaN,NaN,30.0,<NA>,NaN,16500.0,NaN,NaN
1,2.0,NaN,35.0,asimmons@garza.com,España,16500.0,2026-05-04,No
2,3.0,George Burke,40.0,mcclainerin@gmail.com,Argentina,16500.0,2026-01-27,NaN
3,4.0,Joyce Williams,30.0,<NA>,Argentina,25000.0,2025-02-23,No
5,6.0,David Rodriguez Jr.,25.0,timothyjohnson@yahoo.com,España,16500.0,2025-06-16,No
...,...,...,...,...,...,...,...,...
113,114.0,Jackson Simpson,30.0,hharris@choi.com,España,18000.0,2024-06-13,Sí
114,115.0,Michelle Hart,35.0,ajones@wilson.com,Argentina,25000.0,2025-12-22,No
115,116.0,Samuel Roth,30.0,robertsmith@taylor.info,España,12000.0,2024-12-10,Sí
116,117.0,Kristina Buchanan,30.0,rmurphy@gmail.com,Argentina,18000.0,2024-11-18,No
119,120.0,Christopher Mendoza,30.0,myerssteven@moore-george.info,NaN,16500.0,2026-03-01,No

In [32]:
dfCrudoCopia["correo_valido"] = dfCrudoCopia ["correo"].str.contains("@",na=False)

In [33]:
dfCrudoCopia.head(5)

,id,nombre,edad,correo,pais,salario,fecha_registro,activo,correo_valido
0,NaN,NaN,30.0,<NA>,NaN,16500.0,NaN,NaN,False
1,2.0,NaN,35.0,asimmons@garza.com,España,16500.0,2026-05-04,No,True
2,3.0,George Burke,40.0,mcclainerin@gmail.com,Argentina,16500.0,2026-01-27,NaN,True
3,4.0,Joyce Williams,30.0,<NA>,Argentina,25000.0,2025-02-23,No,False
5,6.0,David Rodriguez Jr.,25.0,timothyjohnson@yahoo.com,España,16500.0,2025-06-16,No,True

In [35]:
dfCrudoCopia["pais"].isnull().sum()

np.int64(32)

In [39]:
pais_moda = dfCrudoCopia["pais"].mode()[0]

In [40]:
dfCrudoCopia["pais"] = dfCrudoCopia["pais"].fillna(pais_moda)

In [41]:
dfCrudoCopia["pais"].isnull().sum()

np.int64(0)

In [42]:
dfCrudoCopia.dtypes

id                float64
nombre             object
edad              float64
correo             object
pais               object
salario           float64
fecha_registro     object
activo             object
correo_valido        bool
dtype: object

In [43]:
dfCrudoCopia["fecha_registro"] = pd.to_datetime(dfCrudoCopia["fecha_registro"])

In [44]:
dfCrudoCopia["fecha_registro"].dtype

dtype('<M8[ns]')

In [45]:
dfCrudoCopia.dtypes

id                       float64
nombre                    object
edad                     float64
correo                    object
pais                      object
salario                  float64
fecha_registro    datetime64[ns]
activo                    object
correo_valido               bool
dtype: object

In [46]:
dfCrudoCopia["activo"].value_counts(dropna=False)

activo
Sí     35
NaN    28
No     27
Name: count, dtype: int64

In [47]:
dfCrudoCopia["activo"] = dfCrudoCopia["activo"].fillna("Sí")

In [48]:
dfCrudoCopia["activo"].value_counts(dropna=False)

activo
Sí    63
No    27
Name: count, dtype: int64

In [49]:
dfCrudoCopia["activo"] = dfCrudoCopia["activo"].map(
    {
        "Sí": 1,
        "No": 0
    })

In [50]:
dfCrudoCopia["activo"].value_counts(dropna=False)

activo
1    63
0    27
Name: count, dtype: int64

# Conclusiones
1. variables duplicadas
2. variables nulos
3. conversiones de datos
4. valores fuera de rango
5. tipos de datos